name: Clockwise CI/CD

on:
  push:
    branches:
      - 'releases/**'
jobs:    
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        clockfaces:
          - cw-cf-0x01
          - cw-cf-0x02
          - cw-cf-0x03
          - cw-cf-0x04
          - cw-cf-0x05
    steps:
    - name: Checkout clockwise
      uses: actions/checkout@v3
      with:
        path: clockwise
        submodules: recursive
    - name: Checkout GitHub Pages
      uses: actions/checkout@v3
      with:
        repository: jnthas/clockwise
        ref: gh-pages
        path: github-pages
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Building ${{ matrix.clockfaces }}
      run: |
        ln -s ../clockfaces/${{ matrix.clockfaces }} $GITHUB_WORKSPACE/clockwise/firmware/lib/${{ matrix.clockfaces }}
        pio run --project-dir clockwise/firmware/
        rm $GITHUB_WORKSPACE/clockwise/firmware/lib/${{ matrix.clockfaces }}
    - name: Publish new version
      run: |
          cd $GITHUB_WORKSPACE/github-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull origin gh-pages
          cp --force $GITHUB_WORKSPACE/clockwise/firmware/.pio/build/esp32dev/firmware.bin static/firmware/${{ matrix.clockfaces }}/firmware.bin
          git add .
          git commit -m "new version published - ${{ matrix.clockfaces }}"
          git push

